/*
 * This source file was generated by the Gradle 'init' task
 */
package com.rnimour.messaging.kafka

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
open class Consumer {
    val greeting: String
        get() {
            return "Hello World! I consume Kafka messages!"
        }
}

fun main(args: Array<String>) {
    println(Consumer().greeting)
    runApplication<Consumer>(*args)
}
